name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Install the latest version of Chrome
      uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Install ChromeDriver for Windows
      uses: nanasess/setup-chromedriver@v1
      if: runner.os == 'Windows'
    - run: chromedriver --url-base=/wd/hub &
      if: runner.os == 'Windows'
    - name: Install ChromeDriver for Ubuntu
      uses: nanasess/setup-chromedriver@v1
      if: runner.os == 'Linux'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
      if: runner.os == 'Linux'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
